### ISSUE TITLE
Unable to run greeter example.

### ISSUE THREAD

**Issue by DiederikvandenB** [micro/kubernetes#24] opened 2018-11-29 23:53 UTC
Hi there! I am trying to run the examples from the repo, but something is not working.

First of all, it seems like the files in `/config/micro` are out of date. They use the deprecated `apiVersion: extensions/v1beta1`, which is now `apiVersion: apps/v1` for deployments (I'm on v1.10.0).

I have updated the configuration files to the settings in this Gist https://gist.github.com/DiederikvandenB/c069ffb7e6416dc40e7ed8710a94bdd6

I then set up port-forwarding like this:
```
➜ kc port-forward services/micro-api 8080:80
```

When I run this requests I get errors:
```
➜ curl -H "Content-Type: application/json" -d '{"name": "me"}' localhost:8080/say/hello
{"id":"go.micro.api","code":500,"detail":"not found","status":"Internal Server Error"}%

➜ curl -H "Content-Type: application/json" -d '{"service": "greeter", "method": "Say.Hello", "name": "me"}' localhost:8080/rpc
{"id":"go.micro.rpc","code":500,"detail":"error during request: Unsupported Content-Type: application/json","status":"Internal Server Error"}%
```

And dropping the content type header here makes no sense of course.

Obviously I am doing something wrong, but I really cannot figure out what it is.

**Comment by DiederikvandenB** [comment] 2018-11-29 23:54
Also, if you want I can prepare a PR to update the kube yamls?

**Comment by asim** [comment] 2018-11-30 01:07
Yea please issue a PR for the updates. I'll have a look at the content type issue in the morning. I believe it's from a recent PR in go-plugins which removed support for them.

**Comment by asim** [comment] 2018-11-30 09:29
Ok yea so this is a different error than the content type one you mentioned before. This error means it can't find the service. With the kubernetes repo, we offload loadbalancing to kubernetes services. This means you need to create a k8s service with the name you're trying to make a request to. In the example the service is called `events` so there would need to be an events service.

The content-type issue is separate which we need to look at. This is because we had a different implementation for grpc which could support many content-types, to be honest we should add this back in but it would then fail to work with standard grpc services which don't understand `application/json`.

**Comment by DiederikvandenB** [comment] 2018-11-30 09:55
Right, so the static selector should take care of this right?

I have uploaded my current kube config here: 
https://gist.github.com/DiederikvandenB/9042cc43c6e1331832b7e86eb94a6dcd

And the code for the auth-svc is:

``` go
package main

import (
	"github.com/gluedev/auth-svc/handler"
	proto "github.com/gluedev/auth-svc/proto"
	"github.com/micro/go-log"
	"github.com/micro/go-micro"
	k8s "github.com/micro/kubernetes/go/micro"
)

func main() {
	service := k8s.NewService(
		micro.Name("auth-svc"),
		micro.Version("latest"),
	)

	// Initialise service
	service.Init()

	// Register Handler
	proto.RegisterAuthHandler(service.Server(), new(handler.Auth))

	// Run service
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}
```

As you can see, the `k8s.newService` name equals the Kubernetes service name `name: auth-svc` in `auth-service.yaml`. Is there something I am missing here?

**Comment by asim** [comment] 2018-11-30 10:05
So if you call the /rpc endpoint this should work I believe. The content type issue might persist so we need to solve that. The micro api currently has a known issue with name resolution as it adds a namespace to whatever you call. We can also fix this as the go-api/resolver should probably be added as a flag/env var.

I'll be offline for an hour. Will come back and help resolve.

**Comment by DiederikvandenB** [comment] 2018-11-30 10:13
Unfortunately not:

```
➜ curl -X POST -H "Content-Type: application/json" -d \
➜ '{
        "service": "auth-svc",
        "method": "Auth.GetUser",
        "request": {}
  }' localhost:8080/rpc

{"id":"go.micro.rpc","code":500,"detail":"error during request: all SubConns are in TransientFailure","status":"Internal Server Error"}%
```

Thanks for your awesome support by the way! 🥇

**Comment by asim** [comment] 2018-11-30 11:15
Ok so the problem is that your application itself is not set to run on port 8080 even though the container port is set to 8080. So the application is likely listening on a random port and not exposed.

**Comment by asim** [comment] 2018-11-30 11:22
We should perhaps provide a way to autodetect the container port and have service bind.

**Comment by DiederikvandenB** [comment] 2018-11-30 11:36
I feel stupid. I thought the `server_address` defaulted to :8080.

However, now I am running in to a next error:

```
{
  "id": "go.micro.rpc",
  "code": 500,
  "detail": "error during request: grpc: failed to unmarshal the received message unexpected EOF",
  "status": "Internal Server Error"
}
```

Could this have something to do with the original issue? If the content-type is incorrect I can imagine RPC has issues unmarshalling.

**Comment by asim** [comment] 2018-11-30 11:40
So this next issue is likely because you need to specify "Content-Type: application/grpc+json" since this kubernetes repo makes use of the grpc plugins and grpc expects this content for grpc.

**Comment by DiederikvandenB** [comment] 2018-11-30 11:48
I was not able to get it working using that header:

```
curl --request POST \
  --url http://localhost:8080/rpc \
  --header 'accept: application/json' \
  --header 'content-type: application/grpc+json' \
  --data '{
	"service": "greeter-srv",
	"method": "Say.Hello",
	"request": {
		"name": "me"
	}
}'
```

Which I think makes sense, since the `/rpc` endpoint requires `json`, but actually only the `request` bit of that is `grpc+json`.

I also cannot query the service directly at `http://localhost:8080/say/hello` (I think the grpc+json might work there) because of the namespace issue. Or is there a way around that?

**Comment by asim** [comment] 2018-11-30 12:06
Yea so this is starting to get a bit tricky and we should simplify the experience as from a user perspective you make a /rpc call with json and assume the api is dealing with the internals whether they be grpc json or something else.

I think our grpc client should handle this seamlessly as opposed to anywhere else. Let's make the changes here https://github.com/micro/go-plugins/tree/master/client/grpc so that the first type of request works.

The other issue related to `http://localhost:8080/say/hello`. This is the namespace issue and to be honest we should also solve this now. Ideally it would be good to resolve both of these issues today as they continue to plague us!

**Comment by asim** [comment] 2018-11-30 12:20
Digging through the code, the client does the right thing and internally sends the right content-type. So this is a none issue. What's causing the issue is the request. We need to figure this part out.

```
{
  "id": "go.micro.rpc",
  "code": 500,
  "detail": "error during request: grpc: failed to unmarshal the received message unexpected EOF",
  "status": "Internal Server Error"
}```

**Comment by DiederikvandenB** [comment] 2018-11-30 12:50
Regarding your last comment, I think you're correct in that the client is not the perpetrator, I believe the error is thrown by the RPC handler:
https://github.com/micro/micro/blob/master/internal/handler/rpc.go#L74

As I started learning Go about last month, my debugging skills are not quite up to par yet, but I am trying my best. I will look in to the namespace issue. What would you propose as a fix? Making it possible for the namespace to be optional?

**Comment by DiederikvandenB** [comment] 2018-11-30 13:04
Also, isn't it strange that when the kubernetes service cannot be found / reached it throws the `TransientFailure`?

Given this line, I would have expected a NotFound error:
https://github.com/micro/go-plugins/blob/master/client/grpc/grpc.go#L63

**Comment by asim** [comment] 2018-11-30 13:32
So the error is a grpc error, as in grpc is trying to make a connection to something that doesn't exist. This is because the selector we use is a "static" selector. It returns the name you pass in with a 8080 port appended. We're offloading the loadbalancing to kubernetes services themselves. So the selector will never return NotFound.

**Comment by asim** [comment] 2018-11-30 13:34
On the namespacing side. This is in https://github.com/micro/go-api. We need to create a flag in the micro toolkit which lets the resolver be set. I'll hack this out now. 

Still not sure about the json decoding issue. Maybe we just avoid converting the string?

**Comment by asim** [comment] 2018-11-30 13:35
When I do this for go-micro it handles it just fine. When I use grpc it barfs.

**Comment by asim** [comment] 2018-11-30 13:58
Ok found a fix for the encoding issue! Pushing now. We weren't setting the grpc content sub type even though we were passing the codec which you'd assume would do it. 

Next let's get the resolver issue fixed.

**Comment by asim** [comment] 2018-11-30 14:01
I pushed this fix https://github.com/micro/go-plugins/commit/270f81ca25f1c8917f969c8581e92e2c187b6d4b

**Comment by DiederikvandenB** [comment] 2018-11-30 14:03
You are awesome! Thanks so much for your great support. I am learning a great deal here.

I am working on a different project now, but later today I will look at the fix (Y).

**Comment by asim** [comment] 2018-11-30 14:05
Cool, thanks. Can I add the company that is using this to the users page?

**Comment by DiederikvandenB** [comment] 2018-11-30 14:14
Definitely. We are Glue and you can find us here https://glue.group

**Comment by asim** [comment] 2018-11-30 14:18
Thank you!

**Comment by DiederikvandenB** [comment] 2018-11-30 17:47
Just wanted to drop a line letting you know that the most recent fix indeed resolved the encoding problem. Amazing!

**Comment by asim** [comment] 2018-11-30 18:13
Great! Now we just need to sort out the resolver. I started looking at it and I'm aware that I need to do a deeper restructure of the go-api code but we need to find a temporary fix to get us past this.

**Comment by asim** [comment] 2018-11-30 20:34
Ok so I have pushed some things to help set the resolver but it doesn't yet give us the ability to specify things correctly. I'm running into design issues where I have a resolver that uses say http host or path to resolve a service name but I may also need an rpc method so I need to figure out a wider thing for that. Could use some design idea help!
 
Code is here https://github.com/micro/go-api/tree/master/resolver

I did however find a fix. If you specify namespace as a blank space then it will set it to nothing e.g `--namespace=' '` or `MICRO_API_NAMESPACE=" "`.

**Comment by asim** [comment] 2018-11-30 20:35
It may just be easier to offload method resolution to the handlers themselves.

**Comment by DiederikvandenB** [comment] 2018-11-30 21:30
I fear I do not understand Micro enough yet to be able to contribute to design ideas, but I'll work our project throughout the weekend, so maybe things will get clearer soon!

On a different subject (if you want me to open another issue, that's fine), I wonder whether the `STATIC_SELECTOR_DOMAIN_NAME` mentioned here https://github.com/micro/go-plugins/tree/master/selector/static makes sense in Kubernetes. I tried it, and it joins the appendix with a dot `.`, which is of course not allowed in Kubernetes service names.

The reason why I want to use it is to add `staging`  or `production` to the service name, so we can instantly make that distinction. So the service `greeter-srv` would get the `greeter-srv-staging` service name.

**Comment by asim** [comment] 2018-11-30 22:16
So here's the documentation on service load balancing https://kubernetes.io/docs/concepts/services-networking/ and the dns functionality here https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/.

When you create a kubernetes service you have to specify a name that only containers letters and dashes. This is used as part of a dns name including a k8s namespace and then a domain. Because we return a just the name, its used as the entry to the dns query. GRPC resolves these names using kube-dns. 

So technically the `STATIC_SELECTOR_DOMAIN_NAME` does work as long as you know what that will be.

My advice would be to use a different namespace per environment like staging and production. Then call greeter.staging or greeter.production. The problem here though is you end up hard coding this in code. The better idea is likely to have your services speak to a fixed name and run them in separate namespace or to do some sort of runtime configuration.

**Comment by asim** [comment] 2018-11-30 22:47
Yes I believe it will. If you are using the web handler feel free to do `MICRO_API_RESOLVER=path` or `--resolver=path`.  That will currently work. The micro/rpc stuff might break.

**Comment by DiederikvandenB** [comment] 2018-12-04 19:51
So I tried what you said, but every request to the web handler would then return a "content-type not supported/provided" error (I can't really remember, sorry). 

Because I did want to continue working on the project, I decided to apply the same quick fix to the web handler like you did for the api:

https://github.com/GlueDev/micro/commit/ea6b7a58c2591374a0d1669be256ed01c34aacc5

If you want, I can submit a PR for this?

**Comment by DiederikvandenB** [comment] 2018-12-04 21:31
No, I have a web service which spits out an thumbnail of an image retrieved from S3. So the call is a simple HTTP call to the endpoint.

With the "fix" from the commit, I am able to run the web handler with `--namespace=" "` and call to:
`localhost:8082/thumbnail-svc/create?key=` and see an image.

**Comment by asim** [comment] 2018-12-04 21:36
You made a change to micro/web not the web handler. The web handler is `--handler=web` which supports web sockets. You can `--handler=http` if you just need a http reverse proxy. What you're attempting to use is a proxy built into the web dashboard which we're supposed to be stripping out.

**Comment by DiederikvandenB** [comment] 2018-12-04 23:03
That makes much more sense. But with the http or the web handler set, I receive a 404 when trying to access the service. I've tried debugging it, but have not gotten really far yet.

Will continue in the morning 👍

**Comment by asim** [comment] 2018-12-04 23:12
Likely because they do not strip the prefixed service name in the path

**Comment by DiederikvandenB** [comment] 2018-12-05 14:21
That makes sense, and I had tried that before posting the comment above. However, I received the same error, but that turned out to be a mistake by me.

Good news is: everything is now running smoothly. Again, thanks so much for the patient support!

**Comment by asim** [comment] 2018-12-05 16:43
No worries. Thanks for working through it with me. Is there anything else left to do?

**Comment by DiederikvandenB** [comment] 2018-12-05 19:23
The HTTP handler only works with the fix I provided in [this comment](https://github.com/micro/kubernetes/issues/24#issuecomment-444467839).

I don't know however if this would break anything else. If you think this is a good idea though, I can submit a PR so I could hop back on to the `microhq/micro:kubernetes` image.

Apart from that, I am all happy 👍

**Comment by asim** [comment] 2018-12-05 19:43
So you're basically stripping service name from the path sent to the end service.  I want this to be configurable rather than hard coded. Anyone currently using this will basically end up with a breaking change.

**Comment by asim** [comment] 2019-01-18 17:32
Closing since we came to a resolution

**Closed by asim** 2019-01-18 17:32 UTC
